### ISSUE TITLE
[iOS][0.74.3] 'react/utils/fnv1a.h' file not found on xcode build

### ISSUE THREAD

**Issue by stephane-r** [ArturKalach/react-native-external-keyboard#40]
Hi Artur :)

I am in the process of migrating my React-Native app (0.74.3) to the new architecture. By activating the module, on iOS only, I have an error when compiling xcode : 

![image](https://github.com/user-attachments/assets/877d8826-8dc7-4040-836c-d1264d0a36ec)

I can't figure out if the problem is with my xcode config or not. I've delete my Pods/Podfile.lock, but same result. 

Maybe the problem is my RN version ? I planned to upgrade to 0.75.x, but it's not that old ^^

I saw on an old issue that you mentioned this problem which was similar: https://github.com/react-native-webview/react-native-webview/issues/3218

Do you have a little idea ? Thank you !

**Comment by ArturKalach** [comment]
Hello @stephane-r,
If I am not mistaken, starting with version `0.74.3`, React Native has enabled `bridgeless` mode by default. Unfortunately, the current version of the package doesn't support `bridgeless` mode, but migration is planned for a future release.

I will check the PR and try to align with `react-native-builder-bob` to ensure that this is the correct solution.

**Comment by stephane-r** [comment]
Thank for your response.

I thought that, by activating the new architecture, bridgeless mode was necessarily disabled ?

**Comment by ArturKalach** [comment]
Hello @stephane-r ,
Thank you very much for the fix. The changes have been added and tested on versions `0.71-0.75` of React Native.

I hope version `0.3.7` will resolve this issue, as it includes your fix and additional lines based on the `react-native-builder-bob` pod example.
