### ISSUE TITLE
 [Invariant Violation: requireNativeComponent: "TextInputFocusWrapper" was not found in the UIManager.]

### ISSUE THREAD

**Issue by Rananjaya** [ArturKalach/react-native-external-keyboard#44]
I got this - [Invariant Violation: requireNativeComponent: "TextInputFocusWrapper" was not found in the UIManager.]

**Comment by ArturKalach** [comment]
Hello @Rananjaya,
It seems that you haven't rebuilt the app after the package installation.

Steps to reproduce:

1. Build and run the app without the package.
2. Install the package.
3. Reload the app.

Observed error:  `Invariant Violation: requireNativeComponent: "TextInputFocusWrapper" was not found in the UIManager.`

<img width="574" alt="image" src="https://github.com/user-attachments/assets/db0be772-1a99-4fb5-9e78-3e1d696c6696">

Resolution:
- Rebuild the app to ensure that the native code has been linked properly.

----------------

Please let me know if you still encounter this error after rebuilding the app.

**Comment by Rananjaya** [comment]
Hi @ArturKalach Thanks for support, the issue is now resolved. However, I have another problem. My text fields are now fully supporting external keyboards, but double-tap and focus are not working anymore. Could you please guide me on how to re-enable these features? Thanks.

  <KeyboardExtendedInput
            style={[styles.textInput, showEyeButton && styles.textInputSecured, updatedStyles?.textInput]}
            placeholderStyle={placeholderStyle}
            {...props}
            secureTextEntry={hideTextSecured}
            selectTextOnFocus={false}
            placeholder={placeholder}
            placeholderTextColor={placeholderTextColor}
            numberOfLines={1}
            selectionColor={'grey'}
            onFocus={handleFocus}
            onBlur={onBlur}
            autoCorrect={false}
            autoComplete={'off'}
            editable={editable}
            accessible={true}
            testID={testID}
            ref={ref}
            {...(v8props?.field || {})}
            focusType={'default'}
          />

**Comment by ArturKalach** [comment]
Dear @Rananjaya 
Thank you for reporting the issue. This problem has been fixed in version 0.3.9.

Unfortunately, this issue occurred as a side effect of the 0.3.8 patch, which fixed [issue #44](https://github.com/ArturKalach/react-native-external-keyboard/issues/44). The new version 0.3.9 contains fixes for both issues.


Regards,
Artur Kalach

**Comment by ArturKalach** [comment]
The issue has been resolved, the new `0.3.10` version is stable and work as expected.

**Comment by Rananjaya** [comment]
@ArturKalach thanks you, after adding this library, we can successfully focus on text fields using the navigation keys, but it doesn't support Tab/Shift+Tab when using an external keyboard. Do you have any suggestions? Thank you!

**Comment by d1fferenz** [comment]
> Dear [@Rananjaya](https://github.com/Rananjaya) Thank you for reporting the issue. This problem has been fixed in version 0.3.9.
> 
> Unfortunately, this issue occurred as a side effect of the 0.3.8 patch, which fixed [issue #44](https://github.com/ArturKalach/react-native-external-keyboard/issues/44). The new version 0.3.9 contains fixes for both issues.
> 
> Regards, Artur Kalach

At first: Thanks for all of your support on a11y!! Your doing RN's Job :D

I think it would be nice to have a note in the installation part of the README to inform any users to rebuild the app after installing this awesome package :) !
