### ISSUE TITLE
Unsupported top level event type error on new architecture

### ISSUE THREAD

**Issue by stephane-r** [ArturKalach/react-native-external-keyboard#47]
Hello Artur :)

After running my app on new architecture, on the emulator (not tryed on real device), i've this error : 

`Unsupported top level event type "topOnKeyPress"` (but with topOnKeyPress too).

I'm on Android emulator with my external keyboard. I've this error only with new architecture enabled. I can get this error just by pressing the keyboard (**topOnKeyPress** event error) or by tap enter on TextInput field (**topOnKeyPress** error).

I've this error by using `<ExternalKeyboardView />` component. After see the native code, i'm not really understand why i've this error on new architecture. Do you have an idea ? I'm on RN `0.74.3`.

Thank you !

**UPDATE** : i've try on other event name (like onKeyUpPress). I no longer have any errors and physical keyboard navigation seems to work again. But I have doubts about a potential fix.

I'm waiting for your opinion before proposing a patch.

**Comment by oleksii-ilchenko** [comment]
@stephane-r Hello! Could you please add more details about fix? I've faced with the same issue.

**Comment by stephane-r** [comment]
I don't think updating my previous message is the solution. Let's wait for Artur's opinion :)

**Comment by oleksii-ilchenko** [comment]
but its better than nothing) could you plz provide it? just for testing? I'll be really grateful

**Comment by stephane-r** [comment]
> but its better than nothing) could you plz provide it? just for testing? I'll be really grateful

Yes. I've try to change some éventName by removing "top" (ex topOnKeyUpPress to onKeyUpPress, in android Events folder). It work for me but i dont know if it can create other problem.

**Comment by oleksii-ilchenko** [comment]
<img width="834" alt="Screenshot 2024-10-10 at 18 07 21" src="https://github.com/user-attachments/assets/fe103819-b4ed-453d-ab9a-434b1305466b">

Here? and thats all?

**Comment by ArturKalach** [comment]
Hello, 
Sorry for the delayed reply. I will try to check it today. Renaming could be an option, as there might be a name collision, and your fix could be what's needed.

Could share the `rn` version?

**Comment by oleksii-ilchenko** [comment]
@ArturKalach 0.75.2. Thanks a loty for investigating!

**Comment by stephane-r** [comment]
> Hello, Sorry for the delayed reply. I will try to check it today. Renaming could be an option, as there might be a name collision, and your fix could be what's needed.
> 
> Could share the `rn` version?

No problem, than your for your response. Since my first post, i've upgrade to latest 0.75.4.
If my proposed fix seems viable to you, I will send a PR with the fixes.

**Comment by ArturKalach** [comment]
I found the reason and will try to add the patch for it today. Sorry, I was just busy with the new version and other tasks in general.

My bad, the repo example is based on react-native@0.7.1 and it works stably. I tested it on version 0.7.5, but probably skipped the newArch.

It seems we need something like this:
```
 @Nullable
  @Override
  public Map<String, Object> getExportedCustomBubblingEventTypeConstants() {
    return MapBuilder.<String, Object>builder()
      .put(
        ON_FOCUS_CHANGE,
        MapBuilder.of(
          "phasedRegistrationNames",
          MapBuilder.of("bubbled", ON_FOCUS_CHANGE)))
      .put(
        ON_ENTER_PRESSED,
        MapBuilder.of(
          "phasedRegistrationNames",
          MapBuilder.of("bubbled", ON_ENTER_PRESSED)))
      .build();
  }
 ```
It was there previously, but I probably removed it during the newArch migration. I will test it and share the results later.

**Comment by stephane-r** [comment]
Don't worry, there is no problem :) I was right to wait for your opinion because my proposed fix was not the right solution.

Thank you Artur !

**Comment by ArturKalach** [comment]
The issue should be fixed in version `react-native-external-keyboard@0.3.11-rc1`. 
I will try to test it tomorrow on `0.71` and once more on `0.75`, and then create a new release.

**Comment by stephane-r** [comment]
Hey,

After upgrade to latest 0.3.11, it work nice. Thank you @ArturKalach !
